default:
  image: node:13.1-alpine
  cache:
    policy: pull
    paths:
      - node_modules/
      - .yarn

stages:
  - setup
  - test
  - deploy

setup_install_deps:
  stage: setup
  script:
    - yarn install
  cache:
    policy: pull-push
    paths:
      - node_modules/
      - .yarn

test_lint:
  stage: test
  dependencies:
    - setup_install_deps
  script:
    - yarn lint:ci

deploy_assets_surge_review:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG-$SURGE_SUBDOMAIN.surge.sh
  script:
    - yarn surge assets/surge https://$CI_ENVIRONMENT_SLUG-$SURGE_SUBDOMAIN.surge.sh
  only:
    - branches
  except:
    - master
